# Change these first
owner: ericdrgn # Your GitHub organization or username
repo: drgnstatus # Your GitHub repository name

# Add your sites here
sites:
  - name: Cloud
    url: https://cloud.drgn.xyz
    icon: https://res.cloudinary.com/drgn/image/upload/v1617220764/favicon_n61otn.png
  - name: Git
    url: https://git.drgn.xyz
    icon: https://res.cloudinary.com/drgn/image/upload/v1617220764/favicon_n61otn.png
  - name: Matrix
    url: https://matrix.drgn.im
    icon: https://res.cloudinary.com/drgn/image/upload/v1617220764/favicon_n61otn.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.drgn.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://res.cloudinary.com/drgn/image/upload/v1617220790/mark_white_kn1y0m.png
  name: Status
  introTitle: "Check the status of various Dragon Systems apps."
  introMessage: Dragon Systems Uptime
  theme: night
  favicon: https://res.cloudinary.com/drgn/image/upload/v1617220764/favicon_n61otn.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ericdrgn/drgnstatus
      
i18n:
  footer: Dragon Systems

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
