# Change these first
owner: ericdrgn # Your GitHub organization or username
repo: drgnstats # Your GitHub repository name

# Add your sites here
sites:
  - name: Cloud
    url: https://cloud.drgn.xyz
  - name: Git
    url: https://git.drgn.xyz
  - name: Matrix
    url: https://matrix.drgn.im

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.drgn.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dragon Systems
  introTitle: "Check the status of various Dragon Systems apps."
  introMessage: Dragon Systems Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ericdrgn/drgnstatus

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
